[build]
  # Build command for the React admin dashboard
  command = "npm run build"
  # Directory with the built files
  publish = "dist"
  # Functions directory for Netlify functions (payment verification)
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Function settings
[functions]
  node_bundler = "esbuild"

# Headers for CORS and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Redirect admin paths to the dashboard
[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200

# Keep API routes for functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
